H3 <- read.csv2(file = "c:/users/Treyn/Documents/H3.csv", sep=",")
str(H3)
barplot(table(H3$TDJ))
hist(H3$TDJ)
boxplot(H3$TDJ)
boxplot(H3$TDJ~H3$Race, las=2)
qqnorm(H3$TDJ)
qqline(H3$TDJ)
by(H3$TDJ, H3$Race, sd)
by(H3$TDJ, H3$Race, mean)
by(H3$TDJ, H3$TP, sd)
by(H3$TDJ, H3$TP, mean)
H3$Race <- relevel(H3$Race, ref="Stronghold")
reg <- lm(TDJ~Race+TP, data=H3)
summary(reg)
drop1(reg, .~., test="F")
qqnorm(resid(reg))
qqline(resid(reg))
par(ask=F)
plot(reg)