H3 <- read.csv2(file = "c:/users/Treyn/Documents/H3.csv", sep=",")
str(H3)
barplot(table(H3$GD))
hist(H3$GD)
boxplot(H3$GD)
boxplot(H3$GD~H3$Faction, las=2)
qqnorm(H3$GD)
qqline(H3$GD)
by(H3$GD, H3$Faction, sd)
by(H3$GD, H3$Faction, mean)
by(H3$GD, H3$TP, sd)
by(H3$GD, H3$TP, mean)
H3$Faction <- relevel(H3$Faction, ref="Stronghold")
reg <- lm(GD~Faction+TP, data=H3)
summary(reg)
drop1(reg, .~., test="F")
qqnorm(resid(reg))
qqline(resid(reg))
par(ask=F)
plot(reg)